name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update npm
        run: sudo npm install -g npm@6
      - cache:
          key: dependency-cache-{{ checksum "package.json" }}
          restore-keys: |
            dependency-cache-{{ checksum "package.json" }}-
      - run: npm install
      - run: npm run test

  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update npm
        run: sudo npm install -g npm@6
      - cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
          restore-keys: |
            dependency-cache-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}-
      - run: npm install
      - run: npm run prepare-integration-tests
      - run: npm run test-integration

workflows:
  build_and_test:
    jobs:
      - test
      - test-integration
