name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies # (2)
        uses: actions/cache@v3
        id: files-cache
        with:
         path: |
           node_modules
           dist/
           ~/.meteor
         key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Restore cached meteor bin
        run: |
          if [ -e ~/.meteor/meteor ]
          then
              echo "Cached Meteor bin found, restoring it"
              sudo cp ~/.meteor/meteor /usr/bin/meteor
          else
              echo "No cached Meteor bin found."
           fi
      - name: Install/Retrieve Meteor
        run:  meteor --version || curl https://install.meteor.com/?release=2.6 | /bin/sh
      - name: Install dependencies # (3)
        if: steps.files-cache.outputs.cache-hit != 'true'
        run: meteor npm ci
      - run: meteor npm run test

#   test-integration:
#     name: Integration Tests
#     runs-on: ubuntu-latest

#       - run: npm run prepare-integration-tests
#       - run: npm run test-integration
#       - uses: actions/cache@v3
#         with:
#           path: |
#             ~/.meteor
#             tests/.__tmp_int
