name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies # (2)
        uses: actions/cache@v3
        id: files-cache
        with:
         path: |
           node_modules
           dist/
           ~/.meteor
         key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install/Retrieve Meteor
        run:
        var="$(~/.meteor/meteor --version)"
        if [[ $var =~ "Meteor 2.6" ]]; then
            echo "Up-to-date"
        else
            curl https://install.meteor.com/?release=2.6 | /bin/sh
        fi
      - name: Install dependencies
        if: steps.files-cache.outputs.cache-hit != 'true'
        run: ~/.meteor/meteor npm ci
      - run: ~/.meteor/meteor npm run test

#   test-integration:
#     name: Integration Tests
#     runs-on: ubuntu-latest

#       - run: npm run prepare-integration-tests
#       - run: npm run test-integration
#       - uses: actions/cache@v3
#         with:
#           path: |
#             ~/.meteor
#             tests/.__tmp_int
