
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        id: files-cache
        with:
         path: |
           node_modules
           dist/
           ~/.meteor
           tests/.__tmp_int
         key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '2.6'
        if: steps.files-cache.outputs.cache-hit != 'true'
      - name: Install NPM Dependencies
        if: steps.files-cache.outputs.cache-hit != 'true'
        run: meteor npm ci
  test:
    needs: build
    name: Integration Tests
    steps:
      - name: Unit Tests
        run: meteor npm run test

  test-integration:
    needs: build
    name: Integration Tests
    steps:
      - run: meteor npm run prepare-integration-tests
      - run: meteor npm run test-integration
